version: '3'
services:

  nginx:
    container_name: nginx
    build: ./nginx
    image: jump2django/nginx
    # restart: always
    ports:
      - "80:80"
    volumes:
      - tmp:/tmp/
      - static:/srv/static
      - ./log/nginx:/var/log/nginx
    depends_on:
      - django
    
  django:
    container_name: django
    build: ./jump2django
    image: jump2django/django
    # restart: always
    # ports:
    #   - "8000:8000"
    volumes:
      - tmp:/tmp/
      - static:/usr/src/app/static
      - ./log/django:/var/log/django

volumes:
  tmp:
  static: